### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by Extarys** [kingstefan26/alabamaEncoder#10] opened 2024-08-07 22:53 UTC
A strange error just started popping up for some videos.

I had a couple of chunks that printed:
```
[488] encoding failed: Metric.VMAF calculation in encoder failed: Could not decode vmaf log: /tmp/probe.20.ivf.vmaflog, ['', '[AVHWDeviceContext @ 0x557dbc803640] Cannot load libcuda.so.1\n[AVHWDeviceContext @ 0x557dbc803640] Could not dynamically load CUDA\nDevice creation failed: -1.\n[h264 @ 0x557dbcb34c80] No support for codec h264 profile 244.\n[h264 @ 0x557dbcb34c80] Failed setup for format vaapi: hwaccel initialisation returned error.\n', '']
```

Note that many chunks were encoded successfully.

And then it eventually crashed:
```
Input Video: 1920x1080 @ 29.97 fps, YUV420P, SDR, 68195.44 Kb/s, H264
Using SVT_AV1 version: SVT-AV1-PSY v2.1.0-A (release)
PSY Release:
Checking files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 536/536 [00:00<00:00, 13572.41file/s]
Traceback (most recent call last):
  File "/home/user/.local/bin/alabamaEncoder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/srv/nfs/encoderqueue/alabamaEncoder/alabamaEncode/cli/__main__.py", line 159, in main
    asyncio.run(job.run_pipeline())  # this runs the whole encoding process
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/srv/nfs/encoderqueue/alabamaEncoder/alabamaEncode/core/job.py", line 197, in run_pipeline
    command_objects = annealing(command_objects, 1000)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/nfs/encoderqueue/alabamaEncoder/alabamaEncode/scene/annel.py", line 30, in annealing
    idx1, idx2 = random.sample(range(len(neighbor_solution)), 2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
Current Session Runtime: 0 second(s), Runtime From Previous Sessions: 1 hour(s) 2891 second(s), Total Runtime: 1 hour(s) 2891 second(s)
```

Trying to resume the transcode result in the above error immediately.

I'm unsure how to use alabamaencoder without vmaf, I tried without it and with `crf` and it used vmaf. Maybe I have another setting that enables it - or there is no way to disable it. I also tried converting to loseless x264 before converting, same issue.
```
alabamaEncoder encode --multiprocess_workers 14 "TMP.mkv" "./2Converted/TMP.webm" --title "TEST" --crf 29 --chunk_order even -previews -stats --tune balanced --grain 8 --dont_encode_audio --video_filters "unsharp=7:7:0.8:7:7:0.8"
```

**Comment by kingstefan26** [comment] 2024-09-22 14:13
it was caused by even chunk ordering trying to reorder less then two scenes, fixed in #b0109ee

**Closed by kingstefan26** 2024-09-22 14:13 UTC
